server:
  port: 9003 #项目端口

spring:
  application:
    name: user-dubbo-serivce
  dubbo:
    server: true
    registry: zookeeper://47.101.144.28:2181
    protocol:
      name: dubbo
      port: 20895

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.101.144.28:3306/pdd?useUnicode=true&characterEncoding=utf8&useSSL=false
#  jackson:
#    default-property-inclusion: non_null
  redis:
    host: 47.101.144.28
    port: 6379
    timeout: 30000


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mappers/*.xml

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"


#  datasource:
#    #      url: jdbc:mysql://127.0.0.1:3306/guns_rest?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
#    url: jdbc:mysql://127.0.0.1:3306/sell_app?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: root
#    filters: log4j,wall,mergeStat
#    driver-class-name: com.mysql.cj.jdbc.Driver

#logging:
#  level.root: info
#  level.com.stylefeng: debug
#  path: logs/
#  file: guns-rest.log
